# Generated by Django 5.0.4 on 2024-11-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(choices=[('ELETRONICO', 'Eletrônico'), ('ROUPA', 'Roupa'), ('ALIMENTO', 'Alimento')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
