# Generated by Django 5.0.4 on 2024-11-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0002_alter_promocao_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={},
        ),
    ]
