# Generated by Django 5.0.4 on 2024-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0003_alter_promocao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
