# Generated by Django 5.0.4 on 2024-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0007_alter_promocao_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='data_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
