# Generated by Django 5.0.4 on 2024-12-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0009_alter_promocao_preco_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='disponibilidade',
        ),
    ]
