# Generated by Django 5.0.4 on 2024-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0010_remove_promocao_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
