# Generated by Django 5.0.4 on 2024-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0011_alter_promocao_nome_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ELETRONICO', 'Eletrônico'), ('ROUPA', 'Roupa'), ('ALIMENTO', 'Alimento')], max_length=20, null=True),
        ),
    ]
