# Generated by Django 5.0.4 on 2024-12-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0012_alter_promocao_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocao',
            unique_together={('nome_produto', 'categoria', 'data_inicio', 'data_termino')},
        ),
    ]
