# Generated by Django 5.0.4 on 2024-12-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0013_alter_promocao_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocao',
            unique_together=set(),
        ),
    ]
